### ISSUE TITLE
[Bug] NaN sendo exibido

### ISSUE THREAD

**Issue by SrTonn** [isabela-aquino/pomodorotime#2]
Hey @isabela-aquino, ao utilizar sua aplicação me deparei com o seguinte problema, foi exibido a mensagem `NaN:NaN` no lugar dos números. O erro aconteceu ao clicar no botão de `play` sem antes ter clicado nos botões de `Work (25m)` ou `Break (5m)`.

Estou enviando abaixo um vídeo demonstrando o problema.

https://user-images.githubusercontent.com/30580384/156784986-e5003f3b-3073-4b9b-a537-910857e4f8dc.mp4

**Comment by isabela-aquino** [comment]
Resolvido
